name: entra-id-example

services:
    web-instance:
        container_name: tomcatweb
        volumes:
            - weblogs:/usr/local/tomcat/logs
        env_file:
            - ./.env
        ports:
            - 127.0.0.1:8080:8080
        restart: always
        image: anhvlttfs/entra-id-example:latest
